version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees: ["glazelf"]
    schedule:
      interval: "monthly"
    groups: 
      next:
        patterns:
          - "*next"
      types:
        patterns:
          - "@types/*"
